In [1]:
import numpy as np
from task3_1 import *

In [ ]:
T_c = 2 / np.log(1 + np.sqrt(2)) 
def m_vs_ave(T = T_c):
    L = 40
    n_sweeps = 10_000_000
    
    E_evolution = np.zeros(n_sweeps)
    M_evolution = np.zeros(n_sweeps)
    n_equilibrium = 2000
    
    # equilibrate:
    spins, _ , _ = run_metropolis(L, n_equilibrium, T)

    # run the simulation:

    _, spin_sums, total_Es = run_metropolis(L, n_sweeps, T, spins=spins)
    
    sample_averages = np.array([1_000, 10_000, 100_000, 1_000_000, 10_000_000])
    M_values = np.zeros(len(sample_averages))
    E_evolution = np.zeros(len(sample_averages))
    M_var = np.zeros(len(sample_averages))
    E_var = np.zeros(len(sample_averages))
    for i in range(len(sample_averages)):
        M_values[i] = np.mean(spin_sums[:sample_averages[i]])
        E_evolution[i] = np.mean(total_Es[:sample_averages[i]])
        M_var[i] = np.var(spin_sums[:sample_averages[i]])
        E_var[i] = np.var(total_Es[:sample_averages[i]])

    np.savez(f'convergence.npz', M_values=M_values, E_evolution=E_evolution, M_var=M_var, E_var=E_var, sample_averages=sample_averages)    

In [ ]:
m_vs_ave()

In [ ]:
data = np.load('convergence2.27.npz')
M_values = data['M_values']
E_evolution = data['E_evolution']
M_var = data['M_var']
E_var = data['E_var']
sample_averages = data['sample_averages']


In [9]:
# here we want the variance in the normalised mag/energy, since it makes for easy comparison to other results
np.set_printoptions(precision=5)
print(sample_averages[1:])
print(M_values[1:])
print(M_var[1:])
print(E_evolution[1:])
print(E_var[1:])

[   10000   100000  1000000 10000000]
[-0.09982  0.31215  0.0314   0.0147 ]
[0.3737  0.32998 0.43037 0.43497]
[-1.41648 -1.42697 -1.42872 -1.43   ]
[0.0059  0.00641 0.00636 0.00628]
