In [93]:
import numpy as np
import matplotlib.pyplot as plt

In [94]:
%matplotlib qt5

In [95]:
plt.rcParams.update({
    "text.usetex": True,  
    "font.family": "serif",
    "font.serif": ["Times"], 
})

def black_text(ax, text, xfrac, yfrac, fontsize=30):
    ax.annotate(
        text, xy=(xfrac, yfrac), fontsize=fontsize, color='black',
        xycoords='axes fraction'
    )

# 3.1(1)

In [96]:
labelsize = 26
ticksize = 22
legendsize = 20

In [97]:
fig, ax = plt.subplots(1, 1, figsize=(15, 5))


data = np.load('M_time_nofield.npz')
Ts = data['Ts']
spin_sums = data['spin_sums']
print(spin_sums)

for i in range(len(Ts)):
    T = Ts[i]
    mag = spin_sums[i]
    steps = np.arange(len(mag))
    ax.scatter(steps, mag, label=f"T = {T}", s = 1)
ax.set_ylim(-1, 1)

[[ 0.015 -0.01   0.007 ...  0.912  0.909  0.88 ]
 [ 0.011 -0.01   0.059 ...  0.194  0.225  0.263]
 [-0.106 -0.125 -0.106 ...  0.014  0.046  0.031]]


(-1.0, 1.0)

In [98]:
ax.legend(fontsize=legendsize)
ax.legend(scatterpoints=1, markerscale=10, fontsize=legendsize, ncol=3, columnspacing=0.01)
ax.tick_params(axis='x', labelsize=ticksize)
ax.tick_params(axis='y', labelsize=ticksize)
ax.set_xlabel(r'\# sweeps', fontsize=labelsize)
ax.set_ylabel(r'M', fontsize=labelsize)

Text(136.88280763542963, 0.5, 'M')

In [99]:
fig.tight_layout()

In [100]:
#fig.savefig('task311.png', dpi=300, bbox_inches='tight')

# 3.1(2)

In [101]:
# data for E and M evolution
data = np.load('E_M_data_pure.npz')
T_range = data['T_range']
E_evolution = data['E_evolution']
M_evolution = data['M_evolution']
data2 = np.load('spin_snapshots_pure.npz')

In [102]:
mosaic = """
    aaa
    bcd
"""

fig, ax_dict = plt.subplot_mosaic(mosaic, figsize=(15,10))

In [103]:
ax1 = ax_dict['a']
ax2 = ax1.twinx()

ax2.scatter(T_range, E_evolution, s=10, label='E', color = 'tab:orange')
ax1.scatter(T_range, M_evolution, s=10, label='M', color = 'tab:blue')

In [104]:
ax1.tick_params(axis='x', labelsize=ticksize)
ax1.tick_params(axis='y', labelsize=ticksize)
ax2.tick_params(axis='y', labelsize=ticksize)
ax1.set_xlabel('T', fontsize=labelsize)
ax1.set_ylabel(r'$\mathrm{|\langle M \rangle|}$', fontsize=labelsize)
ax2.set_ylabel(r'$\mathrm{ \langle E \rangle}$', fontsize=labelsize)

Text(1393.6986922953854, 0.5, '$\\mathrm{ \\langle E \\rangle}$')

In [105]:
handles1, labels1 = ax1.get_legend_handles_labels()
handles2, labels2 = ax2.get_legend_handles_labels()

handles = handles1 + handles2
labels = labels1 + labels2

ax1.legend(handles, labels, scatterpoints=1, markerscale=2, fontsize=legendsize, loc = 'center right')

In [106]:
T_s = data2['T_s']
spin_snapshots = data2['spin_snapshots']

In [107]:
for i in range(len(T_s)):
    T = T_s[i]
    spin_snapshot = spin_snapshots[i]
    ax = ax_dict[chr(98+i)]
    
    ax.imshow(spin_snapshot, cmap='bwr', origin='lower', interpolation='none', vmin=-1, vmax=1)
    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_xlabel(f"T = {T}", fontsize=labelsize)

In [108]:
fig.tight_layout()

In [109]:
#fig.savefig('task312.png', dpi=300, bbox_inches='tight')

# 3.1(2) $T_c$

In [110]:
data = np.load('estimate_tc.npz')
T_c_indexes = data['T_cs']
T_range = data['T_range']
T_c = T_range[T_c_indexes]
C_storage = data['C_storage']

In [111]:
np.set_printoptions(precision=5)
T_c = T_range[T_c_indexes]
T_c

array([2.27655, 2.32064, 2.26653, 2.27455])

In [112]:
theo_tc = 2 / np.log(1 + np.sqrt(2))
relative_error = np.abs((T_c - theo_tc) / theo_tc)
relative_error*100

array([0.32469, 2.2676 , 0.11688, 0.23637])

# 3.1(3)

In [113]:
# note: skalerer C verdiene med L^2 for korrekt normalisering pga. feil i kode som genererer data

fig, axs = plt.subplots(1, 2, figsize=(15, 5), sharey=True)
axs[0].scatter(T_range, C_storage[0]*10**2, s=5, label='L = 10', color = 'tab:blue')
axs[0].scatter(T_range, C_storage[1]*20**2, s=5, label='L = 20', color = 'tab:orange')

axs[1].scatter(T_range, C_storage[2]*30**2, s=5, label='L = 30', color = 'tab:green')
axs[1].scatter(T_range, C_storage[3]*40**2, s=5, label='L = 40', color = 'tab:purple')

x = 2 / (np.log(1 + np.sqrt(2)))
axs[0].axvline(x=x, color='r', linestyle='--', label=r'$\mathrm{T_c}$')
axs[1].axvline(x=x, color='r', linestyle='--', label=r'$\mathrm{T_c}$')

In [114]:
for ax in axs:
    ax.legend(fontsize=legendsize)
    ax.legend(scatterpoints=1, markerscale=5, fontsize=legendsize)
    ax.tick_params(axis='x', labelsize=ticksize)
    ax.tick_params(axis='y', labelsize=ticksize)
    ax.set_xlabel(r'T', fontsize=labelsize)
axs[0].set_ylabel('C', fontsize=labelsize)

Text(147.63401485964093, 0.5, 'C')

In [115]:
fig.tight_layout()

In [116]:
black_text(axs[0], 'a)', 0.02, 0.9, fontsize=labelsize)
black_text(axs[1], 'b)', 0.02, 0.9, fontsize=labelsize)

In [117]:
#fig.savefig('task313.png', dpi=300, bbox_inches='tight')

# 3.1(4)

In [118]:
data = np.load('E_M_C_data_impure2.npz')
T_range = data['T_range']
M_evolutions = data['M_evolutions']
E_evolutions = data['E_evolutions']
C_evolutions = data['C_evolutions']
p_values = data['p_values']

In [119]:
fig, axs = plt.subplots(1, 2, figsize=(15, 5))

In [120]:
axs[0].scatter(T_range, M_evolutions[0], s=5, label=f'p = {p_values[0]}', color = 'tab:blue')
axs[0].scatter(T_range, M_evolutions[1], s=5, label=f'p = {p_values[1]}', color = 'tab:orange')
axs[0].scatter(T_range, M_evolutions[2], s=5, label=f'p = {p_values[2]}', color = 'tab:green')

In [121]:
axs[1].scatter(T_range, E_evolutions[0], s=5, label=f'p = {p_values[0]}', color = 'tab:blue')
axs[1].scatter(T_range, E_evolutions[1], s=5, label=f'p = {p_values[1]}', color = 'tab:orange')
axs[1].scatter(T_range, E_evolutions[2], s=5, label=f'p = {p_values[2]}', color = 'tab:green')

In [122]:
black_text(axs[0], 'a)', 0.02, 0.87, fontsize=labelsize)
black_text(axs[1], 'b)', 0.02, 0.9, fontsize=labelsize)

In [123]:
for ax in axs:
    ax.legend(scatterpoints=1, markerscale=5, fontsize=legendsize)
    ax.tick_params(axis='x', labelsize=ticksize)
    ax.tick_params(axis='y', labelsize=ticksize)
    ax.set_xlabel(r'T', fontsize=labelsize)
axs[0].set_ylabel(r'$|\mathrm{\langle M \rangle}|$', fontsize=labelsize)
axs[1].set_ylabel(r'$\mathrm{\langle E \rangle}$', fontsize=labelsize)

Text(777.8922167955236, 0.5, '$\\mathrm{\\langle E \\rangle}$')

In [124]:
fig.tight_layout()

In [125]:
#fig.savefig('task314_1.png', dpi=300, bbox_inches='tight')

# 3.1(4) contd.

In [126]:
# skalerer C av samme grunn som før
fig, axs = plt.subplots(figsize=(10, 5))
axs.scatter(T_range, C_evolutions[0]*40**2, s=10, label=f'p = {p_values[0]}', color = 'tab:blue')
axs.scatter(T_range, C_evolutions[1]*40**2, s=10, label=f'p = {p_values[1]}', color = 'tab:orange')
axs.scatter(T_range, C_evolutions[2]*40**2, s=10, label=f'p = {p_values[2]}', color = 'tab:green')
x = 2 / (np.log(1 + np.sqrt(2)))
axs.axvline(x=x, color='r', linestyle='--', label=r'$\mathrm{T_c}$')
axs.set_ylim(0, 2)

(0.0, 2.0)

In [127]:

axs.legend(scatterpoints=1, markerscale=2, fontsize=legendsize)
axs.tick_params(axis='x', labelsize=ticksize)
axs.tick_params(axis='y', labelsize=ticksize)
axs.set_xlabel(r'T', fontsize=labelsize)
axs.set_ylabel(r'C', fontsize=labelsize)

Text(85.13401485964091, 0.5, 'C')

In [128]:
fig.tight_layout()

In [129]:
#fig.savefig('task314_2.png', dpi=300, bbox_inches='tight')

# 3.1(5)

In [130]:
data = np.load('SA_data_impure.npz')
E_vals = data['E_vals']
M_vals = data['M_vals']
p_values = data['p_values']
spin_pictures = data['spin_pictures']
mask_pictures = data['mask_pictures']
np.set_printoptions(precision=3)
print(p_values)
print(E_vals)
print(M_vals)

[0.01 0.1  0.2 ]
[[-1.965 -1.965 -1.97 ]
 [-1.64  -1.615 -1.657]
 [-1.395 -1.395 -1.397]]
[[0.991 0.991 0.993]
 [0.739 0.136 0.441]
 [0.076 0.381 0.165]]


In [131]:
spin_pictures[mask_pictures == 1] *= 2

In [132]:
fig, axs = plt.subplots(1, 3, figsize=(15, 5))
axs[0].imshow(spin_pictures[0], cmap='bwr', origin='lower', interpolation='none', vmin=-2, vmax=2)
axs[1].imshow(spin_pictures[1], cmap='bwr', origin='lower', interpolation='none', vmin=-2, vmax=2)
axs[2].imshow(spin_pictures[2], cmap='bwr', origin='lower', interpolation='none', vmin=-2, vmax=2)

axs[0].set_xlabel(f'p = {p_values[0]}', fontsize=labelsize)
axs[1].set_xlabel(f'p = {p_values[1]}', fontsize=labelsize)
axs[2].set_xlabel(f'p = {p_values[2]}', fontsize=labelsize)

for ax in axs:
    ax.set_xticks([])
    ax.set_yticks([])

In [133]:
fig.tight_layout()

In [134]:
#fig.savefig('task315.png', dpi=300, bbox_inches='tight')

# 3.2 (1)

In [135]:
data = np.load('M_time_field.npz')
T = data['T']
spins = data['spins']
mag = data['spin_sum']

In [136]:
fig, axs = plt.subplots(1, 2, figsize=(15, 5))
x_axis = np.arange(len(mag))
axs[0].scatter(x_axis, mag, s=1, label=f'T = {T}', color='tab:orange')
axs[1].imshow(spins, cmap='bwr', origin='lower', interpolation='none', vmin=-1, vmax=1)

In [137]:
axs[0].tick_params(axis='x', labelsize=ticksize)
axs[0].tick_params(axis='y', labelsize=ticksize)
axs[0].set_xlabel(r'\# sweeps', fontsize=labelsize)
axs[0].set_ylabel('M', fontsize=labelsize)
axs[1].set_xlabel(r'\# 10 000', fontsize=labelsize)
axs[0].legend(scatterpoints=1, markerscale=10, fontsize=legendsize)

axs[1].set_xticks([])
axs[1].set_yticks([])

axs[0].set_ylim(-0.3, 1)

(-0.3, 1.0)

In [138]:
fig.tight_layout()

In [139]:
#fig.savefig('task321.png', dpi=300, bbox_inches='tight')

# 3.2 (2)

In [140]:
data = np.load('susceptibility_field2.npz')
T_range = data['T_range']
chi_values = data['chi_values']
M_values = data['M_values']
H_values = data['H_values']

In [141]:
# må skalere her også
fig, axs = plt.subplots(1, 2, figsize=(15, 5))

for i in range(len(H_values)):
    axs[1].scatter(T_range, chi_values[i]*40**2, s=5, label=f'H = {H_values[i]}')
    axs[0].scatter(T_range, np.abs(M_values[i]), s=5, label=f'H = {H_values[i]}')

In [142]:
for ax in axs:
    ax.legend(scatterpoints=1, markerscale=5, fontsize=legendsize)
    ax.tick_params(axis='x', labelsize=ticksize)
    ax.tick_params(axis='y', labelsize=ticksize)
    ax.set_xlabel(r'T', fontsize=labelsize)
axs[1].set_ylabel(r'$\chi$', fontsize=labelsize)
axs[0].set_ylabel(r'$\mathrm{|\langle M \rangle |}$', fontsize=labelsize)
axs[1].set_ylim(0, 35)

(0.0, 35.0)

In [143]:
fig.tight_layout()

In [144]:
black_text(axs[0], 'a)', 0.02, 0.83, fontsize=labelsize)
black_text(axs[1], 'b)', 0.02, 0.9, fontsize=labelsize)

In [145]:
#fig.savefig('task322.png', dpi=300, bbox_inches='tight')

# 3.2(3)

In [146]:
data = np.load('scaling_field2.npz')
T_range = data['T_range']
chi_values = data['chi_scaled_vals']
h_values = data['h_scaled_vals']
H_values = data['H_list']

In [147]:
# version 2, må skalere chi med L^2 av samme grunn som før

fig, ax = plt.subplots(figsize=(15, 5))
T_c = 2 / (np.log(1 + np.sqrt(2)))

for i in range(len(H_values)):
    H = H_values[i]
    below = T_range < T_c
    ax.scatter(h_values[i, below], chi_values[i, below]*40**2, s=5, label = f'H  = {H}, '+ r'$T < T_c$')

for i in range(len(H_values)):
    H = H_values[i]
    above = T_range > T_c
    ax.scatter(h_values[i, above], chi_values[i, above]*40**2, s=5, label = f'H = {H}, '+ r'$T > T_c$') 


ax.legend(scatterpoints=1, markerscale=5, fontsize=legendsize, ncols = 2, columnspacing=0.01)
ax.set_xscale('log')
ax.set_yscale('log')

In [148]:
ax.tick_params(axis='x', labelsize=ticksize)
ax.tick_params(axis='y', labelsize=ticksize)
ax.set_xlabel(r'$h / |t|^{\beta \delta}$', fontsize=labelsize)
ax.set_ylabel(r'$\chi \, |t|^{\gamma}$', fontsize=labelsize)

Text(145.309662333956, 0.5, '$\\chi \\, |t|^{\\gamma}$')

In [149]:
fig.tight_layout()

In [150]:
#fig.savefig('task323.png', dpi=300, bbox_inches='tight')